<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>JLib.Tools</PackageId>
	<Version>1.1.0</Version>
	<Authors>JLib</Authors>
	<Description>Shared utility functions for JLib applications.</Description>
	<RepositoryUrl>https://github.com/jonwrites/DocFramework.FakeLibrary1</RepositoryUrl>
  </PropertyGroup>

</Project>
